export const CharInfo = [
  [      
    {
      id: 1,
      name: 'Belle',
      description: 'In most cases, she deals with a high amount of DPS and has a quick reload speed with low health. She has extremely high / long-ranged electric bolts that also bounce between other enemies. The Super she has fires a marker that deals a low amount of damage but boosts any damage the person will receive who is marked.',
      image: './assets/img/brawl/belle.png',
    },
    {
      id: 2,
      name: 'Bo',
      description: 'Bo lobs an arrow over obstacles that lays three mines on the ground upon landing. The mines are momentarily shown, before becoming invisible to enemies until they are triggered, and the traps are still visible to teammates. They trigger when enemies travel on their radius and explode 1.15 seconds later, dealing damage, destroying nearby obstacles, and knocking back any enemies inside its 2 tile blast radius. When triggered, they will beep and flash before exploding.',
      image: './assets/img/brawl/bo.png',
    },
    {
      id: 3,
      name: 'Brock',
      description: 'Brock is a Common Brawler who is unlocked as a Trophy Road reward upon reaching 1000 Trophies. He has low health but a high damage output. His attack shoots long-ranged rockets that explode and deal area damage in a short radius. His Super fires a barrage of rockets in a large area.',
      image: './assets/img/brawl/brock.png',
    },
    {
      id: 4,
      name: 'Bull',
      description: 'Bull has high health, a fast movement speed, and a high damage output at close range. His Trait allows him to charge his Super from enemies damaging him. His attack is a shot of multiple shotgun shells that deal high damage up close.',
      image: './assets/img/brawl/bull.png',
    },
    {
      id: 5,
      name: 'Colette',
      description: 'Colette is a Chromatic Brawler that could be unlocked as a Brawl Pass reward at Tier 30 from Season 3: Welcome to Starr Park! or can be unlocked from Brawl Boxes. She attacks by firing a projectile that deals more damage the more health her enemy has or a fixed amount against certain targets.',
      image: './assets/img/brawl/Colette.png',
    },
    {
      id: 6,
      name: 'Colt',
      description: 'Colt is a Common Brawler who is unlocked as a Trophy Road reward upon reaching 60 Trophies. He has low health but a high damage output. His attack is a long-ranged volley of six bullets. His Super is a longer-ranged volley of twelve piercing bullets that can destroy obstacles.',
      image: './assets/img/brawl/colt.png',
    },
    {
      id: 7,
      name: 'Dynamike',
      description: 'Dynamike is a Common Brawler who is unlocked as a Trophy Road reward upon reaching 2000 Trophies. He has low health but a high damage output. He attacks by lobbing sticks of dynamite over obstacles that blow up and deal high damage in a medium radius.',
      image: './assets/img/brawl/dynomike.png',
    },
    {
      id: 8,
      name: 'Edgar',
      description: 'Edgar is an Epic Brawler who could be unlocked for free as a Brawlidays 2020 gift from December 19th through January 7th or from Brawl Boxes. He has high and consistent burst damage and great mobility with his Super and his very fast movement speed, but low health and a short attack range.',
      image: './assets/img/brawl/edgar.png',
    },
    {
      id: 9,
      name: 'Gene',
      description: 'His super is a magical hand that grabs and pulls enemies close! Gene is a Mythic Brawler who has a moderate health and damage. For his attack, his lamp spews out a ball of smoke that splits after a certain range. Gene\'s Super pulls an enemy and drags them to Gene\'s location.',
      image: './assets/img/brawl/gene.png',
    },
    {
      id: 10,
      name: 'Jessie',
      description: 'Jessie is a Common Brawler who is unlocked as a Trophy Road reward upon reaching 500 Trophies. She has moderately low health, moderate damage and a rather slow reload speed. Her attack is an electric orb that bounces between enemies.',
      image: './assets/img/brawl/jessie.png',
    },
    {
      id: 11,
      name: 'Leon',
      description: 'Leon is a Legendary Brawler who has moderate health and a high damage output at close range. He attacks by flicking out four Spinner Blades that sweep and deal less damage further away. Leon\'s Super makes him temporarily invisible to enemies.',
      image: './assets/img/brawl/leon.png',
    },
    {
      id: 12,
      name: 'Nita',
      description: 'Nita is a Common Brawler that is unlocked as a Trophy Road reward upon reaching 15 Trophies. She has moderately high health and attacks with shockwaves that have moderate range and can hit multiple enemies.',
      image: './assets/img/brawl/nita.png',
    },
    {
      id: 13,
      name: 'Penny',
      description: 'Penny is a Super Rare Brawler with moderately high health and a variable damage output, but a slow reload speed. Penny\'s attack fires a pouch of gold that deals splash damage when it hits a target.',
      image: './assets/img/brawl/Penny.png',
    },
    {
      id: 13,
      name: 'Rosa',
      description: 'Rosa is a Rare Brawler who has high health and a high damage output. Her attack is a flurry of three short-ranged punches from her boxing gloves. Her Super grants her a momentary but significant damage-reduction shield. Her first Gadget, Grow Light, spawns bushes around herself.',
      image: './assets/img/brawl/rosa.png',
    },
    {
      id: 14,
      name: 'Squeak',
      description: 'Squeak is a Mythic Brawler who has moderate health and a moderate damage output. He attacks by shooting a blob of goo that sticks to obstacles and targets and then explodes after a delay. His Super shoots a giant ball that explodes into six smaller blobs that each explode after a delay, similarly to his main attack.',
      image: './assets/img/brawl/Squeak.png',
    },
    {
      id: 15,
      name: 'Tick',
      description: 'Tick is a metal ball of barely controlled excitement and energy - explosive energy! He throws mines, and his Super makes his head detach, seek a target and explode. Tick is a Common Brawler who is unlocked as a Trophy Road reward upon reaching 4000 Trophies.',
      image: './assets/img/brawl/tick.png',
    },    
  ],

  [
    {
      id: 1,
      name: 'Choji',
      description: 'Chōji is a very kind, polite, and caring person. These characteristics are said to be his greatest strength by both his father Chōza and his former teacher Asuma Sarutobi while his greatest weakness was his lack of self-confidence.',
      image: './assets/img/naruto/choji.png',
    }, 
    {
      id: 2,
      name: 'Deidara',
      description: 'He is a powerful and intelligent ninja with long, blonde hair and bangs, often leading him to be mistaken for or joked about as a girl. More distinctively, he has mouths on the palms of his hands, which he uses to create special bombs out of clay. Indeed, the name Deidara is related to the Japanese word for “mud.”',
      image: './assets/img/naruto/deidara.png',
    }, 
    {
      id: 3,
      name: 'Gaara',
      description: 'Gaara is a sharp and innovative fighter. His large array of sand-based jutsu are crafted by and unique to him. He has an eye for detail, able to quickly identify his opponents vulnerabilities, and acts on his observations with his versatile sand.',
      image: './assets/img/naruto/gaara.png',
    }, 
    {
      id: 4,
      name: 'Gamabunta',
      description: 'Gamabunta is a grumpy and highly apathetic toad. He does not like to take orders from anyone, unless the summoner is highly talented and earns his respect. Jiraiya, Minato and Naruto are three of the few people that he has allowed to ride on top of his head without question.',
      image: './assets/img/naruto/gamabunta.png',
    }, 
    {
      id: 5,
      name: 'Hinata',
      description: 'Hinata is characterised as shy, thoughtful, serene, kind, and very polite, as noted from her always addressing people with proper honourifics, including the Gotei 13 captains. She is also very gentle, a trait that Neji and her father used to consider as a flaw, and dislikes competing and fighting.',
      image: './assets/img/naruto/hinata.png',
    }, 
    {
      id: 6,
      name: 'Ino',
      description: 'Personality. From her childhood, Ino has been as a confident, friendly, bold and outspoken girl, sometimes lashing out at others if their personal habits bother her. She is generally more motivated than her team-mates Shikamaru Nara and Chōji Akimichi and tends to take charge of them.',
      image: './assets/img/naruto/ino.png',
    }, 
    {
      id: 7,
      name: 'Itachi',
      description: 'Itachi is the older brother of Sasuke Uchiha, and is responsible for killing all the members of their clan, sparing only Sasuke. He appears working as a terrorist from the organisation Akatsuki and serves as Sasuke\'s greatest enemy.',
      image: './assets/img/naruto/itachi.png',
    },
    {
      id: 8,
      name: 'Jiraya',
      description: 'Jiraiya is a ninja from the village of Konohagakure trained by Hiruzen Sarutobi, the Third Hokage. He becomes known as the "Toad Sage" due to his training under the Great Toad Sage in the field of Senjutsu (sage techniques), enabling him to summon toads as allies during battles.',
      image: './assets/img/naruto/jiraya.png',
    },
    {
      id: 9,
      name: 'Kakashi',
      description: 'As an adult, Kakashi typically has a relaxed and almost bored attitude, not prone to getting too worked up about anything or by anyone. Despite his increasingly growing reputation and prowess as a ninja, Kakashi has shown no signs of arrogance, and is rather modest about his abilities.',
      image: './assets/img/naruto/kakashi.png',
    },
    {
      id: 10,
      name: 'Kakuzu',
      description: 'Kakuzu is a rogue ninja from the Village Hidden in the Waterfall who became a member of the Akatsuki, serving as their treasurer, and an antagonist in the manga/anime series Naruto. He steals hearts from his victims in order to remain alive and achieve a near-immortal lifespan.',
      image: './assets/img/naruto/kakuzu.png',
    },
    {
      id: 11,
      name: 'Kankuro',
      description: 'Kankuro is an outstanding puppeteer, he uses his skills to attack with his puppets; He didn\'t get on with this younger brother Gaara at first, but as Gaara changed, the two became closer. When Gaara was taken away by Deidara, he chased after his brother despite knowing the dangers.',
      image: './assets/img/naruto/kankuro.png',
    },
    {
      id: 12,
      name: 'Kiba',
      description: 'Kiba is often short-tempered and impulsive (in stark contrast to his teammates Shino and Hinata), and can be prone to making mistakes when he becomes agitated in battle. He also enjoys combat even when facing particularly strong opponents.',
      image: './assets/img/naruto/kiba.png',
    },
    {
      id: 13,
      name: 'Lee',
      description: 'Rock Lee is a shinobi of Konohagakure\'s Lee clan and a member of Team Guy. Unlike most shinobi, he lacked the skills necessary to use ninjutsu or genjutsu. However, he overcomes those shortcomings by undergoing special training from Might Guy that would make him a taijutsu master while still a genin.',
      image: './assets/img/naruto/lee.png',
    },
    {
      id: 14,
      name: 'Naruto',
      description: 'Naruto is generally a very simple minded, easy going, cheerful person. He often rushes things, and misses obvious things such as Hinata\'s constant shyness around him. In the beginning of the series, Naruto is very fun loving, often pulling pranks on fellow villagers.',
      image: './assets/img/naruto/naruto.png',
    },
    {
      id: 15,
      name: 'Neji',
      description: 'Neji Hyūga was a shinobi of Konohagakure\'s Hyūga clan. Though a prodigy even by the Hyūga\'s standards, Neji was a member of the clan\'s branch house; no matter how skilled he became, he would always be in service to the Hyūga\'s main house, a fact that convinced him fate was predetermined.',
      image: './assets/img/naruto/neji.png',
    },
    {
      id: 16,
      name: 'Sarutobi',
      description: 'He was the Third Hokage originally from Konohagakure\'s Sarutobi clan. He was part of Team Tobirama alongside Homura Mitokado and Koharu Utatane under the leadership of the Second Hokage. He was also trained by the First Hokage and would later become the teacher of the Legendary Sannin Tsunade, Jiraiya, and Orochimaru.',
      image: './assets/img/naruto/sarutobi.png',
    },
    {
      id: 17,
      name: 'Sasuke',
      description: 'In personality, sasuke is described as a smart, ambitious, stubborn, likes challenging, and arrogant ninja. He grows in a situation that required him to be the best ninja in order to reach his goal. First, he is a smart ninja. He was born from a family who become the leader of his clan, Uchiha.',
      image: './assets/img/naruto/sasuke.png',
    },
    {
      id: 18,
      name: 'Shikamaru',
      description: 'Shikamaru Nara is a lazy genius. He finds many things in life to be annoying or troublesome and is usually foul mouthed. But, deep down, he is a kind person. Not only is he kind, but he is a genius with an IQ of 200 . He is a brilliant strategist as well as a level-headed thinker.',
      image: './assets/img/naruto/shikamaru.png',
    },
    {
      id: 19,
      name: 'Temari',
      description: 'Personality. Temari is generally overbearing, if not blunt, toward those around her, rarely afraid to speak her mind. Temari is known as the cruelest of the kunoichi, but she does have a caring side and is not above showing concern for others.',
      image: './assets/img/naruto/temari.png',
    },
    {
      id: 20,
      name: 'Sakura',
      description: 'Single, but deeply in love with Sasuke. An aloof, enigmatic loner, Sasuke gives no sign of returning Sakura\'s feelings. But as with all bad boys, Sasuke\'s coldness only makes Sakura more determined to win him over. As she declares to him, "I would do anything for you! So please, just stay with me!"',
      image: './assets/img/naruto/sakura.png',
    },
  ],

  [
    {
      id: 1,
      name: 'Archmage',
      description: 'Hailing from the magical kingdom of Dalaran, the Archmagi represent the pinnacle of magical power. Weaving their intricate enchantments, these crotchety old wizards are called upon to defend humanity with all the magical powers at their disposal.',
      image: './assets/img/warcraft/archmage.png',
    },
    {
      id: 2,
      name: 'Blademaster',
      description: 'The Blademaster is one of the most powerful melee Heroes when combined with Mirror Image and Critical Strike. Blademasters can quickly destroy enemy units and buildings when they are powered up with items and levels.',
      image: './assets/img/warcraft/blademaster.png',
    },
    {
      id: 3,
      name: 'BloodElf',
      description: 'The blood elves (or sin\'dorei in Thalassian ("children of the blood")) were not always part of the Horde. They are a playable race composed of former high elves who renamed themselves in honor of their people who were killed during the siege of Quel\'Thalas by the Scourge during the Third War.',
      image: './assets/img/warcraft/bloodelf.png',
    },
    {
      id: 4,
      name: 'Deathknight',
      description: 'Death Knights were once virtuous defenders of Humanity. However, once the Paladin ranks were disbanded by the failing Alliance, many of these holy warriors traveled to the quarantined lands to ease the suffering of those left within the plague-ridden colonies.',
      image: './assets/img/warcraft/deathknight.png',
    },
    {
      id: 5,
      name: 'Demonhunter',
      description: 'Demon Hunters are dark, shadowy warriors who are shunned by the greater Night Elf society. They made a pact, long ago, to fight against the forces of chaos using its own terrible powers against it.',
      image: './assets/img/warcraft/demonhunter.png',
    },
    {
      id: 6,
      name: 'Dreadlord',
      description: 'Dread Lords are incredibly powerful demons who wield the powers of darkness and mental domination. These cunning, malefic beings once served as the demon Kil\'jaeden\'s most trusted lieutenants.',
      image: './assets/img/warcraft/dreadlord.png',
    },
    {
      id: 7,
      name: 'Farseer',
      description: 'Far Seers are ancient Orcs who represent the pinnacle of Shamanistic power. These powerful Shamans are counted amongst Thrall\'s closest advisors and are constantly in tune with the workings and maneuverings of the Horde. Far Seers are not only tied to the elements of the earth and sky, but are also adept at foretelling the future.',
      image: './assets/img/warcraft/farseer.png',
    },
    {
      id: 8,
      name: 'KeeperOfTheGrove',
      description: 'The Keeper of the Grove is a great Hero! All four of his abilities are extremely useful. Entangling Roots can be used to stop melee units in their tracks allowing the Night Elves to pick them off at range with Archers, Huntresses, or Dryads. Force of Nature can be used to create Treants, which can complement your army. Force of Nature can also be used to remove trees allowing you to reach Gold Mines surrounded by trees. Thorns are very useful when facing lots of melee units. ',
      image: './assets/img/warcraft/KeeperOfTheGrove.png',
    },
    {
      id: 9,
      name: 'Lich',
      description: 'The Lich is a great first or second Hero mainly for his Frost Nova ability. Frost Nova is one of the uber abilities in the game, especially when combined with the Archmage\'s Brilliance Aura, Mana Potions, or Dark Ritual. Frost Armor can be useful on allied Heroes, Abominations, or Frost Wyrms.',
      image: './assets/img/warcraft/lich.png',
    },
    {
      id: 10,
      name: 'MountainKing',
      description: 'The Mountain Kings, or Thanes as they are known in Khaz Modan, are the mightiest Dwarven warriors under the mountain. Wielding both enchanted warhammers and hand axes, these fierce fighters live to test themselves against worthy opponents.',
      image: './assets/img/warcraft/Mountainking.png',
    },
    {
      id: 11,
      name: 'CryptLord',
      description: 'A warrior Hero, adept at summoning insect minions and crushing enemies. Betraying the Nerubian people, the Crypt Lords have sacrificed the lifeblood of thousands to bolster the Undead armies of Ner\'zhul, winning an eternal life of servitude in his name. Attacks land units.',
      image: './assets/img/warcraft/CryptLord.png',
    },
    {
      id: 12,
      name: 'Paladin',
      description: 'Disenfranchised and driven from their former homes, the Paladins still work selflessly to protect humanity from the gnawing jaws of evil. Empowered by the Light, these mighty warriors brandish both warhammer and holy fire in battle against all who would trample the meek and innocent.',
      image: './assets/img/warcraft/paladin.png',
    },
    {
      id: 13,
      name: 'MoonPriestess',
      description: 'The fearless leaders of the Sentinel army, the Priestesses of the Moon epitomize the power and grace of their race\'s ancient Moon Goddess, Elune. The Priestesses, equipped with silvery, glowing armor, ride the fearless Frostsaber tigers of Winterspring into battle.',
      image: './assets/img/warcraft/MoonPriestess.png',
    },
    {
      id: 14,
      name: 'ShadowHunter',
      description: 'A cunning Hero, adept at healing magics and voodoo curses. Channeling the spirits of their dark gods, the Shadow Hunters walk the line between darkness and light in the hope of salvaging the future for their savage brethren.',
      image: './assets/img/warcraft/ShadowHunter.png',
    },
    {
      id: 15,
      name: 'TaurenChieftain',
      description: 'The tauren chieftains are elder tauren warriors that lead their tribes in daily life as well as in battle. Ceremoniously decked with the ancient totems of their tribes, chiefs uphold the honor and simplicity of tauren culture. ',
      image: './assets/img/warcraft/TaurenChieftain.png',
    },
    {
      id: 16,
      name: 'Warden',
      description: 'The Warden is an assassination type Hero that can require a lot of skill to use. Unlike the Demon Hunter, she can\'t take the same amount of damage before dying. She lacks the Immolation and Evasion abilities and other bonuses that allow the Demon Hunter to survive in melee combat much longer.',
      image: './assets/img/warcraft/warden.png',
    },
  ]
];


export const audioArr = [
  ['./assets/audio/bs/Belle1.mp3', './assets/audio/bs/Belle2.mp3', './assets/audio/bs/Belle3.mp3', './assets/audio/bs/Belle4.mp3', './assets/audio/bs/Bo1.mp3',
  './assets/audio/bs/Bo2.mp3', './assets/audio/bs/Bo3.mp3', './assets/audio/bs/Bo4.mp3', './assets/audio/bs/Brock1.mp3', './assets/audio/bs/Brock2.mp3',
  './assets/audio/bs/Brock3.mp3', './assets/audio/bs/Brock4.mp3', './assets/audio/bs/Bull1.mp3', './assets/audio/bs/Bull2.mp3', './assets/audio/bs/Bull3.mp3',
  './assets/audio/bs/Bull4.mp3', './assets/audio/bs/Colette1.mp3', './assets/audio/bs/Colette2.mp3', './assets/audio/bs/Colette3.mp3', './assets/audio/bs/Colette4.mp3',
  './assets/audio/bs/Colt1.mp3', './assets/audio/bs/Colt2.mp3', './assets/audio/bs/Colt3.mp3', './assets/audio/bs/Colt4.mp3', './assets/audio/bs/Dynamike1.mp3',
  './assets/audio/bs/Dynamike2.mp3', './assets/audio/bs/Dynamike3.mp3', './assets/audio/bs/Dynamike4.mp3', './assets/audio/bs/Edgar1.mp3', './assets/audio/bs/Edgar2.mp3',
  './assets/audio/bs/Edgar3.mp3', './assets/audio/bs/Edgar4.mp3', './assets/audio/bs/Gene1.mp3', './assets/audio/bs/Gene2.mp3', './assets/audio/bs/Gene3.mp3',
  './assets/audio/bs/Gene4.mp3', './assets/audio/bs/Jessie1.mp3', './assets/audio/bs/Jessie2.mp3', './assets/audio/bs/Jessie3.mp3', './assets/audio/bs/Jessie4.mp3',
  './assets/audio/bs/Leon1.mp3', './assets/audio/bs/Leon2.mp3', './assets/audio/bs/Leon3.mp3', './assets/audio/bs/Leon4.mp3', './assets/audio/bs/Nita1.mp3',
  './assets/audio/bs/Nita2.mp3', './assets/audio/bs/Nita3.mp3', './assets/audio/bs/Nita4.mp3', './assets/audio/bs/Penny1.mp3', './assets/audio/bs/Penny2.mp3',
  './assets/audio/bs/Penny3.mp3', './assets/audio/bs/Penny4.mp3', './assets/audio/bs/Rosa1.mp3', './assets/audio/bs/Rosa2.mp3', './assets/audio/bs/Rosa3.mp3',
  './assets/audio/bs/Rosa4.mp3', './assets/audio/bs/squeak1.mp3', './assets/audio/bs/squeak2.mp3', './assets/audio/bs/tick1.mp3', './assets/audio/bs/tick2.mp3',
  './assets/audio/bs/tick3.mp3', './assets/audio/bs/tick4.mp3' ],
  ['./assets/audio/naruto/Choji.mp3', './assets/audio/naruto/Deidara.mp3', './assets/audio/naruto/Gaara.mp3', './assets/audio/naruto/Gamabunta.mp3', './assets/audio/naruto/Hinata.mp3',
  './assets/audio/naruto/Ino.mp3', './assets/audio/naruto/Itachi1.mp3', './assets/audio/naruto/Itachi.mp3', './assets/audio/naruto/Jiraya.mp3', './assets/audio/naruto/Kakashi.mp3',
  './assets/audio/naruto/Kakashi1.mp3', './assets/audio/naruto/Kakashi2.mp3', './assets/audio/naruto/Kakuzu.mp3', './assets/audio/naruto/Kankuro.mp3', './assets/audio/naruto/Kiba.mp3',
  './assets/audio/naruto/Lee.mp3', './assets/audio/naruto/Naruto1.mp3', './assets/audio/naruto/Neji.mp3', './assets/audio/naruto/Neji1.mp3','./assets/audio/naruto/Neji2.mp3', 
  './assets/audio/naruto/Sakura.mp3', './assets/audio/naruto/Sarutobi.mp3', './assets/audio/naruto/Sasuke.mp3', './assets/audio/naruto/Shikamaru.mp3', './assets/audio/naruto/Shikamaru1.mp3', 
  './assets/audio/naruto/Temari.mp3'
  ],
  ['./assets/audio/wc/Archmage0.wav', './assets/audio/wc/Archmage1.wav', './assets/audio/wc/Archmage2.wav', './assets/audio/wc/Archmage3.wav', './assets/audio/wc/Archmage4.wav',
  './assets/audio/wc/Archmage5.wav', './assets/audio/wc/Blademaster0.wav', './assets/audio/wc/Blademaster1.wav', './assets/audio/wc/Blademaster2.wav', './assets/audio/wc/Blademaster3.wav',
  './assets/audio/wc/Blademaster4.wav', './assets/audio/wc/BloodElf0.wav', './assets/audio/wc/BloodElf1.wav', './assets/audio/wc/BloodElf2.wav',
  './assets/audio/wc/BloodElf3.wav', './assets/audio/wc/BloodElf4.wav', './assets/audio/wc/BloodElf5.wav', './assets/audio/wc/CryptLord0.wav', './assets/audio/wc/CryptLord1.wav', 
  './assets/audio/wc/CryptLord2.wav', './assets/audio/wc/CryptLord3.wav', './assets/audio/wc/CryptLord4.wav', './assets/audio/wc/CryptLord5.wav', './assets/audio/wc/DeathKnight0.wav',
  './assets/audio/wc/DeathKnight1.wav', './assets/audio/wc/DeathKnight2.wav', './assets/audio/wc/DeathKnight3.wav', './assets/audio/wc/DeathKnight4.wav', './assets/audio/wc/DeathKnight5.wav',
  './assets/audio/wc/DemonHunter0.wav', './assets/audio/wc/DemonHunter1.wav', './assets/audio/wc/DemonHunter2.wav', './assets/audio/wc/DemonHunter3.wav', './assets/audio/wc/DemonHunter4.wav',
  './assets/audio/wc/DemonHunter5.wav', './assets/audio/wc/Dreadlord0.wav', './assets/audio/wc/Dreadlord1.wav', './assets/audio/wc/Dreadlord2.wav', './assets/audio/wc/Dreadlord3.wav',
  './assets/audio/wc/Dreadlord4.wav', './assets/audio/wc/Dreadlord5.wav', './assets/audio/wc/Farseer0.wav', './assets/audio/wc/Farseer1.wav', './assets/audio/wc/Farseer2.wav',
  './assets/audio/wc/Farseer3.wav', './assets/audio/wc/Farseer4.wav', './assets/audio/wc/Farseer5.wav', './assets/audio/wc/KeeperOfTheGrove0.wav', './assets/audio/wc/KeeperOfTheGrove1.wav',
  './assets/audio/wc/KeeperOfTheGrove2.wav', './assets/audio/wc/KeeperOfTheGrove3.wav', './assets/audio/wc/KeeperOfTheGrove4.wav', './assets/audio/wc/KeeperOfTheGrove5.wav', './assets/audio/wc/Lich0.wav',
  './assets/audio/wc/Lich1.wav', './assets/audio/wc/Lich2.wav', './assets/audio/wc/Lich3.wav', './assets/audio/wc/Lich4.wav', './assets/audio/wc/Lich5.wav',
  './assets/audio/wc/MoonPriestess0.wav', './assets/audio/wc/MoonPriestess1.wav', './assets/audio/wc/MoonPriestess2.wav', './assets/audio/wc/MoonPriestess3.wav', './assets/audio/wc/MoonPriestess4.wav',
  './assets/audio/wc/MoonPriestess5.wav', './assets/audio/wc/MountainKing0.wav', './assets/audio/wc/MountainKing1.wav', './assets/audio/wc/MountainKing2.wav', './assets/audio/wc/MountainKing3.wav',
  './assets/audio/wc/MountainKing4.wav', './assets/audio/wc/MountainKing5.wav', './assets/audio/wc/Paladin0.wav', './assets/audio/wc/Paladin1.wav', './assets/audio/wc/Paladin2.wav',
  './assets/audio/wc/Paladin3.wav', './assets/audio/wc/Paladin4.wav', './assets/audio/wc/Paladin5.wav', './assets/audio/wc/ShadowHunter0.wav', './assets/audio/wc/ShadowHunter1.wav',
  './assets/audio/wc/ShadowHunter2.wav', './assets/audio/wc/ShadowHunter3.wav', './assets/audio/wc/ShadowHunter4.wav', './assets/audio/wc/ShadowHunter5.wav', './assets/audio/wc/TaurenChieftain0.wav',
  './assets/audio/wc/TaurenChieftain1.wav',  './assets/audio/wc/TaurenChieftain3.wav', './assets/audio/wc/TaurenChieftain4.wav', './assets/audio/wc/TaurenChieftain5.wav',
  './assets/audio/wc/Warden0.wav', './assets/audio/wc/Warden1.wav', './assets/audio/wc/Warden2.wav', './assets/audio/wc/Warden3.wav', './assets/audio/wc/Warden4.wav',
  './assets/audio/wc/Warden5.wav'
  ]
];



